### ISSUE TITLE
性能怎么样?

### ISSUE THREAD

**Issue by rfyiamcool** [suiyunonghen/DxValue#1]
建议给出一个性能报告，最少有个参照.  谢谢

**Comment by suiyunonghen** [comment]
里面有一个简单的性能测试的Test，比原生的快，和那个json-iterator的性能差不多，然后Msgpack的话，才写完，还未做相关的测试，其实这个项目的最主要目标也不是性能，性能过得去就好，最主要的是做一个相应的容器，提供相关的操作方法，而不用针对的都定义出相关的Struct然后来序列化匹配
后面慢慢的我会加上一些性能比对的test

**Comment by suiyunonghen** [comment]
加了几个库的性能测试对比，解码的json-iterator最快，编码的，貌似我的最快。反正马马虎虎吧

**Comment by rfyiamcool** [comment]
ok， 辛苦辛苦。 既然用这类兼容库，只要性能不是太过分的差，都是可以接受的。
